config/routes.rb
Rails.application.routes.draw do

  root :to => "application#home"

  get "locations/geocode" => "locations#geocode"

  get "search" => "locations#search"
  # get "locations/search" => "locations#search"


  resources :experiences
  resources :locations


  devise_for :users, :controllers => { omniauth_callbacks: "omniauth_callbacks" }

  devise_scope :user do
     get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :user



  resources :locations, only: [:show, :index, :edit] do
    resources :comments, only: [:show, :create, :new]
  end



  get "user_experiences" => "experiences#user_index"


end

app/models/experience.rb
class Experience < ApplicationRecord

  belongs_to :user

  belongs_to :location

  validates :story, presence: true

  accepts_nested_attributes_for :location



  def location_attributes=(location_attributes)

    self.build_location(location_attributes)
    # self.create_location(location_attributes)
    self.save
  end




  def self.search(search)
    if Location.find_by(:city => "#{search}")
      Location.find_by(:city => "#{search}").experiences
    else
      nil
    end
  end


end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController

    def index
      @experiences = Experience.all

      respond_to do |format|
        format.json { render json: @experiences}
        format.html { render :index }
      end
    end


    def user_index
      @experiences = current_user.experiences

      respond_to do |format|
        format.json { render json: @experiences}
        format.html { render :user_index }
      end
    end


    def new
      @experience = Experience.new
      @experience.build_location
      @locations = Location.all
    end


    def show
      @experience = Experience.find_by_id(params[:id])
    end


    def create
      # binding.pry
      if params[:experience][:location_id].empty?
        @experience = Experience.create(experience_params)
      else
        @experience = Experience.create(story: experience_params[:story], user_id: experience_params[:user_id], location_id: experience_params[:location_id])
      end

      @experience.save
      if @experience.valid?
          render "/application/home"
          # redirect_to experience_path(@experience)
      else
        redirect_to new_experience_path
      end

    end


    def edit
      @experience = Experience.find_by_id(params[:id])
    end


    def update
      @experience = Experience.find(params[:id])
      @experience.update(experience_params)
      redirect_to experience_path(@experience)
    end


    private

      def experience_params
          params.require(:experience).permit(:story, :user_id, :location_id, location_attributes: [:name, :city, :country, :zipcode, :address])
      end


end

app/helpers/experiences_helper.rb
module ExperiencesHelper



end

app/views/experiences/_experience.html.erb
<div>
<% @experiences.each do |experience| %>
  <div><%= link_to experience.story, experience_path(experience)%> </div>

  <% end %>

</div>

app/views/experiences/edit.html.erb
<div class="ui small form">



    <h5>Experience form</h5>
    <%= form_tag experience_path(@experience), method: "put" do %>

    <label>Experience </label>
      <%= text_area_tag :'experience[name]', @experience.story %><br>
      <br><br>
      <%= submit_tag "Update experience" %>
    <% end %>

</div>

app/views/experiences/index.html.erb
<div class="show">
      <div class="experiences">
      <br><br>

      <h4 class="all_experiences"><strong> The Collective Experience </strong></h4>

        <br>
        <p>All Experiences:</p>
          <% Experience.all.each do |experience| %>
            <p><%= link_to experience.story, experience_path(experience)%> </p>
          <% end %>

    </div>
</div>

app/views/experiences/new.html.erb
<div>
    <div class="ui small form">
        <%= form_for @experience do |f| %>
            <%= f.hidden_field :user_id, value: "#{current_user.id}" %>
            <!-- <%= f.label :Experience %><br> -->
            <h5><strong>New Experience: </strong></h5><%= f.text_area :story %><br><br>
        Location:
            <%= f.collection_select :location_id, @locations, :id, :name, include_blank: true, class: "ui dropdown" %></br>
    </div>
</div>
<br>
<br>




<div class="ui small form">

  <p onLoad=" LoadOnce() ">Plot A New Location:</p>

      <%= f.fields_for :location do |location| %>
          <%= location.label :name %>
          <%= location.text_field :name %>
          <%= location.label :address %>
          <%= location.text_field :address %>
          <%= location.label :city %>
          <%= location.text_field :city %>
          <%= location.label :zipcode %>
          <%= location.text_field :zipcode %>
          <%= location.label :country %>
          <%= location.text_field :country %>
          <% end %>
            <br><br>
            <%= f.submit :class => 'ui button' %>
      <% end %>

</div>

app/views/experiences/show.html.erb
<div class="experience_story" >
      <h4><%= @experience.story %></h4>

      <br>
      <br>
      <br><h5>Location:</h5>
      <p><%= link_to @experience.location.name, location_path(@experience.location) %><p>
          <p><%= @experience.location.name %></p>
          <p><%= @experience.location.city %></p>

</div>

app/views/experiences/user_index.html.erb
<% @experiences.each do |exp| %>

  <%= exp.story %>

  <% end %>