config/routes.rb
Rails.application.routes.draw do

  root :to => "application#home"

  get "locations/geocode" => "locations#geocode"

  get "search" => "locations#search"
  # get "locations/search" => "locations#search"


  resources :experiences
  resources :locations


  devise_for :users, :controllers => { omniauth_callbacks: "omniauth_callbacks" }

  devise_scope :user do
     get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :user



  resources :locations, only: [:show, :index, :edit] do
    resources :comments, only: [:show, :create, :new]
  end



  get "user_experiences" => "experiences#user_index"


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || root_path
  end

  def home
    # binding.pry

  end


  # ____google login____
  #
  # protect_from_forgery with: :exception
  # helper_method :current_user
  #
  # def current_user
  #   @current_user ||= User.find(session[:user_id]) if session[:user_id]
  # end


end

app/views/application/home.html.erb
<div class="home_page">

  <%= link_to "Share New Experience |", new_experience_path, :id => "new_experience" %></a>
  <%= link_to "Share New Location |", new_location_path, :id => "new_location" %></a>
  <%= link_to "View Locations |", locations_path, :id => "view_locations" %></a>
  <%= link_to "View Experiences", experiences_path, :id => "view_experiences" %></a>


      <div id="google" style='width: 800px;'>
        <br>
        <br>
        <br>
        <div id="map" style='width: 800px; height: 400px;'></div>


      </div>

      <script src="//maps.google.com/maps/api/js?key=AIzaSyCehDc7T3H1o8tHz5DqIyr6O41l_QCy0ck"></script>
      <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
      <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->


</div>