config/routes.rb
Rails.application.routes.draw do

  root :to => "application#home"

  get "locations/geocode" => "locations#geocode"

  get "search" => "locations#search"
  # get "locations/search" => "locations#search"


  resources :experiences
  resources :locations


  devise_for :users, :controllers => { omniauth_callbacks: "omniauth_callbacks" }

  devise_scope :user do
     get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :user



  resources :locations, only: [:show, :index, :edit] do
    resources :comments, only: [:show, :create, :new]
  end



  get "user_experiences" => "experiences#user_index"


end

app/models/location.rb
class Location < ApplicationRecord

  has_many :experiences

  has_many :users, :through => :experiences

  has_many :comments




  # validates_presence_of :name, :address, :city, :country

    # -----------------------------------------
      # with an attributes
    geocoded_by :address # address is an attribute of MyModel

    # or with a method
    geocoded_by :full_address # full_address is a method which take some model's attributes to get a formatted address for example

    # the callback to set longitude and latitude
    after_validation :geocode

    # the full_address method
    def full_address
      "#{address}, #{zipcode}, #{city}, #{country}"
    end

    # -----------------------------------------


  def self.search(search)
    # binding.pry

    search_term = search.split(" ").map{|l| l.capitalize}.join(" ")
    if self.find_by(:city => search_term)
      self.find_by(:city => search_term).experiences
    else
      nil
    end
  end

  # def self.search(search)
  #   search_term_one = search.split(" ").map{|l| l.capitalize}.join(" ")
  #   search_term_two = search.split(" ").map{|l| l.downcase}.join(" ")
  #   if self.find_by(:city => search_term_one) || self.find_by(:city => search_term_two)
  #     experiences = []
  #     if self.find_by(:city => search_term_one)
  #       experiences << self.find_by(:city => search_term_one).experiences
  #     end
  #     if self.find_by(:city => search_term_two)
  #       experiences << self.find_by(:city => search_term_two).experiences
  #     end
  #   else
  #     nil
  #   end
  # end


end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

    def geocode
      locations = Location.geocoded
      @location_latitudes = locations.map{ |l| {lng: l.longitude, lat: l.latitude} }
      render json: @location_latitudes
    end

    def new
      @location = Location.new
    end


    def show
      @location = Location.find_by_id(params[:id])
      respond_to do |format|
        format.json { render json: @location}
        format.html { render :show }
      end
    end


    def create
      # binding.pry
      @location = Location.new(location_params)
       @location.save
      if @location.valid?
        render :home
      else
        render :new
      end
    end


    def edit
      @location = Location.find_by_id(params[:id])
    end


    def update
      @location = Location.find(params[:id])
      @location.update(location_params)
      redirect_to location_path(@location)
    end


    def index
      @locations = Location.all
      respond_to do |format|
        format.json { render json: @locations }
        format.html { render :index }
      end
    end


    def search
      if params[:search]
        if !(Location.search(params[:search]).nil?) && !(Location.search(params[:search]).empty?)
          @response = Location.search(params[:search])

          render json: @response
        else
          render plain: "No experiences found"
        end
      end
    end


    private

      def location_params
        params.require(:location).permit(:search, :name, :city, :address, :zipcode, :country)
      end


end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_location.html.erb
<div>
<% @locations.each do |location| %>
<% location.each do |l| %>
  <div><%= link_to location.experience.story, experience_path(location.experience)%> </div>

  <% end %>
  <% end %>

</div>

app/views/locations/edit.html.erb
<div class="ui small form">

    <h3>Update Location</h3>

    <div class="location_update">

        <%= form_for(@location) do |f| %>
          <label>Location Name:</label><br>
          <%= f.text_field :name %><br>

          <label>City</label><br>
          <%= f.text_field :city %><br>

          <label>State</label><br>
          <%= f.text_field :state %><br>

          <label>Address</label><br>
          <%= f.text_field :address %><br>

          <br>
          <%= f.submit class: "tiny ui button"%>
        <% end %>

    </div>

</div>

app/views/locations/index.html.erb
<div class="show">

    <div class="locations">
      <br><br>

          <p class="all_locations"><strong> All Locations </strong></p>

          <% @locations.each do |location| %>
            <p><%= link_to location.name, location_path(location)%></p>
          <% end %>

  </div>
</div>

app/views/locations/new.html.erb
<p><%= @location.name %></p>
<% if @location.errors.any? %>
  <!-- <div id="error_explanation"> -->
    <div class="errors" >
      <%= pluralize(@location.errors.count, "error") %>
      prohibited this post from being saved: <br>

        <% @location.errors.full_messages.each do |msg| %>
          <%= msg %><br>
        <% end %>

    </div>
  <% end %>


<div class="location_new">

  <div class="ui small form">

      <h3> New Location </h3>
      <br>
      <br>

      <%= form_for @location, html: {class: "ui small form"} do |f| %>
        <%= f.label :name %><br>
        <%= f.text_field :name %><br>
        <%= f.label :address %><br>
        <%= f.text_field :address %><br><br>
        <%= f.label :zipcode %><br>
        <%= f.text_field :zipcode %><br><br>
        <%= f.label :city %><br>
        <%= f.text_field :city %><br>
        <%= f.label :country %><br>
        <%= f.text_field :country %><br><br>     
        <%= f.submit class: "ui button" %>

     <% end %>

    </div>
</div>

app/views/locations/search.html.erb
<div class="errors">

<% if @experiences.present? %>
  <%= render @experiences %>
<% elsif @none_found == "none" %>
  <p>There are no experiences containing the term(s) <%= params[:search] %>.</p>
<% end %>

</div>

app/views/locations/show.html.erb
<div class="location_show">
  <h5>Location:</h5>
    <%= @location.name %><br>
    <%= @location.city %><br>
    <%= @location.state %><br>
    <%= @location.address %><br>
</div>

<br>
<br>


<div class="location_experiences">
  <h5>The Collective Experience(s): <h5>
      <% @location.experiences.each do |exp| %>
      <%= exp.story %><br>
      <br>
      <% end %>
</div>


<br>
<br>
<br>
<br>
<br>

<div class="location_comments">

      <p>Latest Comment:</p>

      <% @location.comments.each do |comment| %>
          <%= link_to comment.content, location_comment_path(comment) %><br>
        <% end %>

        <%= link_to "Post Comment", new_location_comment_path(@location) %>

</div>